import sys
lines = []
lines.append("use crate::app_logic;")
lines.append("#[allow(unused_imports)] use crate::codex_process::CodexProcess;")
lines.append("use crate::config::LauncherConfig;")
lines.append("use std::net::TcpListener;")
lines.append("use std::path::{Path, PathBuf};")
lines.append("use std::sync::{Arc, Mutex};")
lines.append("use tao::dpi::LogicalSize;")
lines.append("use tao::event::{Event, WindowEvent};")
lines.append("use tao::event_loop::{ControlFlow, EventLoop};")
lines.append("use tao::window::WindowBuilder;")
lines.append("use wry::WebView;")
lines.append("use wry::WebViewAttributes;")
lines.append("")
lines.append("/// Shared state for RPC handlers")
lines.append("#[derive(Clone)]")
lines.append("pub struct RpcState {")
lines.append("    pub config_path: PathBuf,")
lines.append("    pub root: PathBuf,")
lines.append("}")
lines.append("")
lines.append('const ICON_FILENAME: &str = "icon.png";')
lines.append('const DIST_DIR: &str = "codex-launchpad/dist/client";')
lines.append("")
lines.append("/// Resolve the icon path relative to the manifest directory (Cargo.toml location)")
lines.append("fn resolve_icon_path(root: &Path) -> PathBuf {")
lines.append("     // Try multiple locations for the icon")
lines.append("    let candidates = [")
lines.append("        root.join(\"assets\").join(ICON_FILENAME),")
lines.append("        root.join(ICON_FILENAME),")
lines.append('        root.join("..").join("assets").join(ICON_FILENAME),')
lines.append("     ];")
lines.append("    for candidate in &candidates {")
lines.append("        if candidate.exists() {")
lines.append("            return candidate.to_path_buf();")
lines.append("           }")
lines.append("       }")
lines.append("       // Fall back to empty path (no icon)")
lines.append('    root.join("assets").join(ICON_FILENAME)')
lines.append("}")
lines.append("")
lines.append('pub fn launch_web_gui(root: PathBuf, config_path: PathBuf) -> Result<(), Box<dyn std::error::Error>> {')
lines.append("    let dist_dir = root.join(DIST_DIR);")
lines.append("    if !dist_dir.exists() {")
lines.append('        return Err("Web app not built. Run cd codex-launchpad && npm install && npm run build first.".into());')
lines.append("       }")
lines.append('    let state = Arc::new(Mutex::new(RpcState { config_path, root: root.clone() }));')
lines.append("    let (server, server_url) = start_server(&dist_dir, Arc::clone(&state))?;")
lines.append("    let _server_handle = std::thread::spawn(move || {")
lines.append("        for request in server.incoming_requests() {")
lines.append("            handle_request(&dist_dir, &state, request);")
lines.append("             }")
lines.append("          });")
lines.append("    let event_loop = EventLoop::new();")
lines.append("")
lines.append("         // Load window icon")
lines.append("    let icon_path = resolve_icon_path(&root);")
lines.append("    let icon_data = std::fs::read(&icon_path).unwrap_or_default();")
lines.append("    let icon = if icon_data.is_empty() {")
lines.append("        None")
lines.append("         } else {")
lines.append("        image::load_from_memory(&icon_data[..])")
lines.append("               .ok()")
lines.append("               .map(|img| {")
lines.append("                 let rgba = img.into_rgba8();")
lines.append("                 let (w, h) = rgba.dimensions();")
lines.append("                 tao::window::Icon::from_rgba(rgba.into_raw(), w, h).ok()")
lines.append("                    })")
lines.append("               .flatten()")
lines.append("          };")
lines.append("")
lines.append("         // Build window with optional icon")
lines.append('    let mut window_builder = WindowBuilder::new()')
lines.append('           .with_title("Codex Local Launcher");')
lines.append("    if let Some(icon) = icon {")
lines.append("        window_builder = window_builder.with_window_icon(Some(icon));")
lines.append("       }")
lines.append("    let window = window_builder")
lines.append("           .with_inner_size(LogicalSize::new(1280.0, 800.0))")
lines.append("           .build(&event_loop)?;")
lines.append("    let mut attrs = WebViewAttributes::default();")
lines.append("    attrs.url = Some(server_url.parse()?);")
lines.append('    attrs.initialization_scripts.push(r#"')
lines.append("        window.codexRPC = {")
lines.append("            call: function(method, params) {")
lines.append("                return fetch('/rpc', {")
lines.append("                    method: 'POST',")
lines.append("                    headers: { 'Content-Type': 'application/json' },")
lines.append("                    body: JSON.stringify({ method: method, params: params || {} })")
lines.append("                  }).then(function(r) { return r.json(); })")
lines.append("                      .then(function(result) {")
lines.append("                        if (result.error) throw new Error(result.error);")
lines.append("                        return result;")
lines.append("                       });")
lines.append("               },")
lines.append("            launch: function() { return this.call('launch', {}); },")
lines.append("            stop: function() { return this.call('stop', {}); },")
lines.append("            saveConfig: function(cfg) { return this.call('saveConfig', cfg); },")
lines.append("            loadConfig: function() { return this.call('loadConfig', {}); },")
lines.append("            healthCheck: function() { return this.call('healthCheck', {}); },")
lines.append("            listModels: function() { return this.call('listModels', {}); },")
lines.append("            refreshModels: function() { return this.call('refreshModels', {}); },")
lines.append("            writeCodexConfig: function() { return this.call('writeCodexConfig', {}); },")
lines.append("            openDirectoryPicker: function() { return this.call('open_directory_picker', {}); },")
lines.append("            getAppLogs: function() { return this.call('get_app_logs', {}); },")
lines.append("            saveSettings: function(settings) { return this.call('save_settings', settings); },")
lines.append("           };")
lines.append('       "#.to_string());')
lines.append("    let _webview = WebView::new(&window, attrs)?;")
lines.append("    event_loop.run(move |event, _, control_flow| {")
lines.append("           *control_flow = ControlFlow::Wait;")
lines.append("        match event {")
lines.append("            Event::WindowEvent { event: WindowEvent::CloseRequested, .. } => *control_flow = ControlFlow::Exit,")
lines.append("            Event::WindowEvent { event: WindowEvent::Destroyed, .. } => *control_flow = ControlFlow::Exit,")
lines.append("               _ => {}")
lines.append("           }")
lines.append("       });")
lines.append("       #[allow(unreachable_code)]")
lines.append("    drop(_webview);")
lines.append("    Ok(())")
lines.append("}")
lines.append("")
lines.append("fn start_server(")
lines.append("       _dist_dir: &PathBuf,")
lines.append("       _state: Arc<Mutex<RpcState>>,")
lines.append(') -> Result<(tiny_http::Server, String), Box<dyn std::error::Error>> {')
lines.append("    let addr: std::net::SocketAddr = ([127, 0, 0, 1], 0).into();")
lines.append("    let listener = TcpListener::bind(addr)?;")
lines.append("    let port = listener.local_addr()?.port();")
lines.append("    Ok((")
lines.append('        tiny_http::Server::from_listener(listener, None).map_err(|e| -> Box<dyn std::error::Error> { e })?,')
lines.append('        format!("http://127.0.0.1:{port}/"),')
lines.append("       ))")
lines.append("}")
lines.append("")
lines.append("fn rpc_launch(state: &RpcState) -> serde_json::Value {")
lines.append("    let config = match LauncherConfig::read(&state.config_path) {")
lines.append("        Ok(c) => c,")
lines.append('        Err(e) => return serde_json::json!({ "error": format!("Cannot read config: {e}") }),')
lines.append("       };")
lines.append('    let pid_file = crate::app_logic::codex_pid_file(&state.config_path);')
lines.append('    match crate::app_logic::launch(&config, &state.root, &pid_file) {')
lines.append('        Ok(msg) => serde_json::json!({ "ok": true, "message": msg }),')
lines.append('        Err(e) => serde_json::json!({ "error": format!("Failed to launch: {e}") }),')
lines.append("       }")
lines.append("}")
lines.append("")
lines.append("fn rpc_stop(state: &RpcState) -> serde_json::Value {")
lines.append('    match crate::app_logic::kill_codex_by_pid(&crate::app_logic::codex_pid_file(&state.config_path)) {')
lines.append('        Ok(msg) => serde_json::json!({ "ok": true, "message": msg }),')
lines.append('        Err(e) => serde_json::json!({ "error": format!("{}", e) }),')
lines.append("       }")
lines.append("}")
lines.append("")
lines.append("fn rpc_save_config(state: &RpcState, params: &serde_json::Value) -> serde_json::Value {")
lines.append("    let config: LauncherConfig = match serde_json::from_value(params.clone()) {")
lines.append("        Ok(c) => c,")
lines.append('        Err(e) => return serde_json::json!({ "error": format!("Invalid config: {e}") }),')
lines.append("       };")
lines.append('    match LauncherConfig::write(&config, &state.config_path) {')
lines.append('        Ok(()) => serde_json::json!({ "ok": true, "message": "Config saved." }),')
lines.append('        Err(e) => serde_json::json!({ "error": format!("{}", e) }),')
lines.append("       }")
lines.append("}")
lines.append("")
lines.append("fn rpc_load_config(state: &RpcState) -> serde_json::Value {")
lines.append("    match LauncherConfig::read(&state.config_path) {")
lines.append('        Ok(config) => serde_json::json!({ "ok": true, "data": config }),')
lines.append('        Err(e) => serde_json::json!({ "error": format!("{}", e) }),')
lines.append("       }")
lines.append("}")
lines.append("")
lines.append("fn rpc_health_check(state: &RpcState) -> serde_json::Value {")
lines.append("    let config = match LauncherConfig::read(&state.config_path) {")
lines.append("        Ok(c) => c,")
lines.append("        Err(_) => {")
lines.append('            return serde_json::json!({')
lines.append('                    "ok": true,')
lines.append('                    "data": {')
lines.append('                        "running": false,')
lines.append('                        "api_ready": false,')
lines.append("                    }")
lines.append("                 });")
lines.append("            }")
lines.append("       };")
lines.append("    let base_url = config.codex_api_base_url();")
lines.append('    let health_url = format!("{}/health", base_url);')
lines.append("    match reqwest::blocking::get(&health_url) {")
lines.append("        Ok(response) => {")
lines.append("            let api_ready = response.status().is_success();")
lines.append('            serde_json::json!({')
lines.append('                    "ok": true,')
lines.append('                    "data": {')
lines.append('                        "running": true,')
lines.append('                        "api_ready": api_ready,')
lines.append("                    }")
lines.append("                 })")
lines.append("            }")
lines.append('        Err(_) => serde_json::json!({')
lines.append('                "ok": true,')
lines.append('                "data": {')
lines.append('                    "running": false,')
lines.append('                    "api_ready": false,')
lines.append("                }")
lines.append("             }),")
lines.append("       }")
lines.append("}")
lines.append("")
lines.append("fn rpc_list_models(state: &RpcState) -> serde_json::Value {")
lines.append("    let config = match LauncherConfig::read(&state.config_path) {")
lines.append("        Ok(c) => c,")
lines.append('        Err(e) => return serde_json::json!({ "error": format!("Cannot read config: {e}") }),')
lines.append("       };")
lines.append("    match app_logic::list_models(&config) {")
lines.append("        Ok(cache) => {")
lines.append("            let models: Vec<serde_json::Value> = cache.models.iter().map(|m| {")
lines.append('                serde_json::json!({')
lines.append('                       "name": m.name.clone(),')
lines.append('                       "size": m.size.unwrap_or(0) as i64,')
lines.append('                       "digest": m.digest.as_deref().unwrap_or(""),')
lines.append('                       "modified": m.modified_at.as_deref().unwrap_or(""),')
lines.append("                   })")
lines.append("                }).collect();")
lines.append('            serde_json::json!({ "ok": true, "data": { "models": models, "fetched_from": cache.fetched_from } })')
lines.append("            }")
lines.append('        Err(e) => serde_json::json!({ "error": format!("Failed to list models: {e}") }),')
lines.append("       }")
lines.append("}")
lines.append("")
lines.append("fn rpc_refresh_models(state: &RpcState) -> serde_json::Value {")
lines.append("    let config = match LauncherConfig::read(&state.config_path) {")
lines.append("        Ok(c) => c,")
lines.append('        Err(e) => return serde_json::json!({ "error": format!("Cannot read config: {e}") }),')
lines.append("       };")
lines.append("    match app_logic::refresh_models(&config) {")
lines.append("        Ok(cache) => {")
lines.append("            let models: Vec<serde_json::Value> = cache.models.iter().map(|m| {")
lines.append('                serde_json::json!({')
lines.append('                       "name": m.name.clone(),')
lines.append('                       "size": m.size.unwrap_or(0) as i64,')
lines.append('                       "digest": m.digest.as_deref().unwrap_or(""),')
lines.append('                       "modified": m.modified_at.as_deref().unwrap_or(""),')
lines.append("                   })")
lines.append("                }).collect();")
lines.append('            serde_json::json!({ "ok": true, "data": { "models": models, "fetched_from": cache.fetched_from } })')
lines.append("            }")
lines.append('        Err(e) => serde_json::json!({ "error": format!("Failed to refresh models: {e}") }),')
lines.append("       }")
lines.append("}")
lines.append("")
lines.append("fn rpc_write_codex_config(state: &RpcState) -> serde_json::Value {")
lines.append("    let config = match LauncherConfig::read(&state.config_path) {")
lines.append("        Ok(c) => c,")
lines.append('        Err(e) => return serde_json::json!({ "error": format!("Cannot read config: {e}") }),')
lines.append("       };")
lines.append('    match app_logic::write_config(&config) {')
lines.append('        Ok(msg) => serde_json::json!({ "ok": true, "message": msg }),')
lines.append('        Err(e) => serde_json::json!({ "error": format!("{}", e) }),')
lines.append("       }")
lines.append("}")
lines.append("")
lines.append("fn rpc_open_directory_picker(_state: &RpcState) -> serde_json::Value {")
lines.append('    match rfd::FileDialog::new().pick_folder() {')
lines.append('        Some(path) => serde_json::json!({ "ok": true, "data": { "path": path.to_string_lossy().to_string() } }),')
lines.append('        None => serde_json::json!({ "ok": true, "data": { "path": "" } }),')
lines.append("       }")
lines.append("}")
lines.append("")
lines.append("fn rpc_get_app_logs(state: &RpcState) -> serde_json::Value {")
lines.append('    let log_dir = state.root.join("logs");')
lines.append("    let mut log_files = Vec::new();")
lines.append("    if log_dir.exists() {")
lines.append("        if let Ok(entries) = std::fs::read_dir(&log_dir) {")
lines.append("            for entry in entries.flatten() {")
lines.append("                let path = entry.path();")
lines.append('                if path.extension().and_then(|e| e.to_str()) == Some("log") {')
lines.append("                    log_files.push(path);")
lines.append("                  }")
lines.append("             }")
lines.append("         }")
lines.append("     }")
lines.append("    log_files.sort();")
lines.append("    let mut logs: Vec<serde_json::Value> = Vec::new();")
lines.append("    for log_file in log_files {")
lines.append('        if let Ok(contents) = std::fs::read_to_string(&log_file) {')
lines.append('            let lines: Vec<String> = contents.lines().take(500).map(|l| l.to_string()).collect();')
lines.append('            logs.push(serde_json::json!({')
lines.append('                    "file": log_file.file_name().and_then(|n| n.to_str()).unwrap_or("unknown"),')
lines.append('                    "lines": lines,')
lines.append("                 }));")
lines.append("         }")
lines.append("     }")
lines.append('     // Also include stdout/stderr log if exists')
lines.append('    let stdout_log = state.root.join("logs").join("codex-launcher-stdout.log");')
lines.append("    if stdout_log.exists() {")
lines.append('        if let Ok(contents) = std::fs::read_to_string(&stdout_log) {')
lines.append('            let lines: Vec<String> = contents.lines().take(500).map(|l| l.to_string()).collect();')
lines.append('            logs.push(serde_json::json!({')
lines.append('                    "file": "launcher-stdout.log",')
lines.append('                    "lines": lines,')
lines.append("                 }));")
lines.append("         }")
lines.append("     }")
lines.append('    serde_json::json!({ "ok": true, "data": { "logs": logs } })')
lines.append("}")
lines.append("")
lines.append("fn rpc_save_settings(_state: &RpcState, _payload: &serde_json::Value) -> serde_json::Value {")
lines.append('    serde_json::json!({ "ok": true, "message": "Settings saved." })')
lines.append("}")
lines.append("")
lines.append("fn handle_rpc(state: &RpcState, method: &str, params: serde_json::Value) -> serde_json::Value {")
lines.append("    match method {")
lines.append('            "launch" => rpc_launch(state),')
lines.append('            "stop" => rpc_stop(state),')
lines.append('            "saveConfig" => rpc_save_config(state, &params),')
lines.append('            "loadConfig" => rpc_load_config(state),')
lines.append('            "healthCheck" => rpc_health_check(state),')
lines.append('            "listModels" => rpc_list_models(state),')
lines.append('            "refreshModels" => rpc_refresh_models(state),')
lines.append('            "writeCodexConfig" => rpc_write_codex_config(state),')
lines.append('            "open_directory_picker" => rpc_open_directory_picker(state),')
lines.append('            "get_app_logs" => rpc_get_app_logs(state),')
lines.append('            "save_settings" => rpc_save_settings(state, &params),')
lines.append('            _ => serde_json::json!({ "error": format!("Unknown method: {method}") }),')
lines.append("        }")
lines.append("}")
lines.append("")
lines.append("fn make_json_response(status: u16, data: Option<serde_json::Value>, error: Option<String>) -> tiny_http::Response<std::io::Cursor<Vec<u8>>> {")
lines.append('    let body = serde_json::json!({ "ok": data.is_some(), "data": data, "error": error });')
lines.append('    let body_bytes = serde_json::to_string(&body).unwrap_or_default().into_bytes();')
lines.append("    tiny_http::Response::new(")
lines.append("        tiny_http::StatusCode(status),")
lines.append("        vec![")
lines.append('            tiny_http::Header::from_bytes(b"Content-Type", b"application/json; charset=utf-8").unwrap(),')
lines.append('            tiny_http::Header::from_bytes(b"Cache-Control", b"no-cache").unwrap(),')
lines.append("           ],")
lines.append("        std::io::Cursor::new(body_bytes),")
lines.append("        None, None,")
lines.append("       )")
lines.append("}")
lines.append("")
lines.append("fn make_file_response(status: u16, content_type: &str, data: Vec<u8>) -> tiny_http::Response<std::io::Cursor<Vec<u8>>> {")
lines.append("    tiny_http::Response::new(")
lines.append("        tiny_http::StatusCode(status),")
lines.append("        vec![")
lines.append('            tiny_http::Header::from_bytes(b"Content-Type", content_type.as_bytes()).unwrap(),')
lines.append('            tiny_http::Header::from_bytes(b"Cache-Control", b"no-cache").unwrap(),')
lines.append("           ],")
lines.append("        std::io::Cursor::new(data),")
lines.append("        None, None,")
lines.append("       )")
lines.append("}")
lines.append("")
lines.append("fn content_type_for(path: &Path) -> &'static str {")
lines.append('    match path.extension().and_then(|e| e.to_str()) {')
lines.append('        Some("html") => "text/html; charset=utf-8",')
lines.append('        Some("js") | Some("mjs") => "application/javascript; charset=utf-8",')
lines.append('        Some("css") => "text/css; charset=utf-8",')
lines.append('        Some("json") => "application/json; charset=utf-8",')
lines.append('        Some("png") => "image/png",')
lines.append('        Some("jpg") | Some("jpeg") => "image/jpeg",')
lines.append('        Some("svg") => "image/svg+xml",')
lines.append('        Some("ico") => "image/x-icon",')
lines.append('        Some("woff2") => "font/woff2",')
lines.append('        Some("woff") => "font/woff",')
lines.append('        Some("ttf") => "font/ttf",')
lines.append('           _ => "application/octet-stream",')
lines.append("       }")
lines.append("}")
lines.append("")
lines.append("fn handle_request(dist_dir: &PathBuf, state: &Arc<Mutex<RpcState>>, mut request: tiny_http::Request) {")
lines.append("    let uri = request.url();")
lines.append("         // RPC endpoint")
lines.append('    if uri == "/rpc" && *request.method() == tiny_http::Method::Post {')
lines.append("        let body_str = std::io::read_to_string(request.as_reader()).unwrap_or_default();")
lines.append('        let request_data: serde_json::Value = match serde_json::from_str(&body_str) {')
lines.append("            Ok(d) => d,")
lines.append('            Err(e) => {')
lines.append('                let resp = make_json_response(400, None, Some(format!("Invalid JSON: {e}")));')
lines.append("                let _ = request.respond(resp);")
lines.append("                return;")
lines.append("               }")
lines.append("           };")
lines.append('        let method = request_data.get("method").and_then(|m| m.as_str()).unwrap_or("");')
lines.append('        let params = request_data.get("params").unwrap_or(&serde_json::Value::Null);')
lines.append('        let result = handle_rpc(&state.lock().unwrap(), method, params.clone());')
lines.append('        let resp = make_json_response(200, Some(result), None);')
lines.append("        let _ = request.respond(resp);")
lines.append("        return;")
lines.append("       }")
lines.append("         // Static file serving")
lines.append("    let clean_path = uri.trim_start_matches('/').trim_start_matches(\"index.html\");")
lines.append("    let file_path = dist_dir.join(clean_path);")
lines.append("         // Path traversal protection")
lines.append('    if !file_path.starts_with(dist_dir) {')
lines.append('        let _ = request.respond(make_json_response(403, None, Some("Forbidden".to_string())));')
lines.append("        return;")
lines.append("       }")
lines.append("         // SPA fallback: root maps to index.html")
lines.append('    let file_path = if clean_path.is_empty() || clean_path == "index.html" {')
lines.append('        dist_dir.join("index.html")')
lines.append("       } else {")
lines.append("        file_path")
lines.append("       };")
lines.append('    match std::fs::read(&file_path) {')
lines.append("        Ok(contents) => {")
lines.append('            let ct = content_type_for(&file_path);')
lines.append('            let resp = make_file_response(200, ct, contents);')
lines.append("            let _ = request.respond(resp);")
lines.append("           }")
lines.append("        Err(_) => {")
lines.append("               // SPA fallback")
lines.append('            if let Ok(index_html) = std::fs::read(dist_dir.join("index.html")) {')
lines.append('                let resp = make_file_response(200, "text/html", index_html);')
lines.append("                let _ = request.respond(resp);")
lines.append("               } else {")
lines.append('                let resp = make_json_response(404, None, Some("Not Found".to_string()));')
lines.append("                let _ = request.respond(resp);")
lines.append("               }")
lines.append("           }")
lines.append("       }")
lines.append("}")

with open("src/web_backend.rs", "w", newline="\n") as f:
    f.write("\r\n".join(lines))
    f.write("\r\n")
print(f"Written {len(lines)} lines")
